/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.pineone.icbms.sda.comm.kafka.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class COL_ONEM2M extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"COL_ONEM2M\",\"namespace\":\"com.pineone.icbms.sda.comm.kafka.avro\",\"fields\":[{\"name\":\"col_from\",\"type\":[\"null\",\"string\"]},{\"name\":\"read_from_time\",\"type\":[\"null\",\"string\"]},{\"name\":\"write_queue_time\",\"type\":[\"null\",\"string\"]},{\"name\":\"task_group_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"task_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"start_time\",\"type\":[\"null\",\"string\"]},{\"name\":\"calcuate_latest_yn\",\"type\":[\"null\",\"string\"]},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":[\"null\",\"string\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence col_from;
  @Deprecated public java.lang.CharSequence read_from_time;
  @Deprecated public java.lang.CharSequence write_queue_time;
  @Deprecated public java.lang.CharSequence task_group_id;
  @Deprecated public java.lang.CharSequence task_id;
  @Deprecated public java.lang.CharSequence start_time;
  @Deprecated public java.lang.CharSequence calcuate_latest_yn;
  @Deprecated public java.util.List<java.lang.CharSequence> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public COL_ONEM2M() {}

  /**
   * All-args constructor.
   */
  public COL_ONEM2M(java.lang.CharSequence col_from, java.lang.CharSequence read_from_time, java.lang.CharSequence write_queue_time, java.lang.CharSequence task_group_id, java.lang.CharSequence task_id, java.lang.CharSequence start_time, java.lang.CharSequence calcuate_latest_yn, java.util.List<java.lang.CharSequence> data) {
    this.col_from = col_from;
    this.read_from_time = read_from_time;
    this.write_queue_time = write_queue_time;
    this.task_group_id = task_group_id;
    this.task_id = task_id;
    this.start_time = start_time;
    this.calcuate_latest_yn = calcuate_latest_yn;
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return col_from;
    case 1: return read_from_time;
    case 2: return write_queue_time;
    case 3: return task_group_id;
    case 4: return task_id;
    case 5: return start_time;
    case 6: return calcuate_latest_yn;
    case 7: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: col_from = (java.lang.CharSequence)value$; break;
    case 1: read_from_time = (java.lang.CharSequence)value$; break;
    case 2: write_queue_time = (java.lang.CharSequence)value$; break;
    case 3: task_group_id = (java.lang.CharSequence)value$; break;
    case 4: task_id = (java.lang.CharSequence)value$; break;
    case 5: start_time = (java.lang.CharSequence)value$; break;
    case 6: calcuate_latest_yn = (java.lang.CharSequence)value$; break;
    case 7: data = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'col_from' field.
   */
  public java.lang.CharSequence getColFrom() {
    return col_from;
  }

  /**
   * Sets the value of the 'col_from' field.
   * @param value the value to set.
   */
  public void setColFrom(java.lang.CharSequence value) {
    this.col_from = value;
  }

  /**
   * Gets the value of the 'read_from_time' field.
   */
  public java.lang.CharSequence getReadFromTime() {
    return read_from_time;
  }

  /**
   * Sets the value of the 'read_from_time' field.
   * @param value the value to set.
   */
  public void setReadFromTime(java.lang.CharSequence value) {
    this.read_from_time = value;
  }

  /**
   * Gets the value of the 'write_queue_time' field.
   */
  public java.lang.CharSequence getWriteQueueTime() {
    return write_queue_time;
  }

  /**
   * Sets the value of the 'write_queue_time' field.
   * @param value the value to set.
   */
  public void setWriteQueueTime(java.lang.CharSequence value) {
    this.write_queue_time = value;
  }

  /**
   * Gets the value of the 'task_group_id' field.
   */
  public java.lang.CharSequence getTaskGroupId() {
    return task_group_id;
  }

  /**
   * Sets the value of the 'task_group_id' field.
   * @param value the value to set.
   */
  public void setTaskGroupId(java.lang.CharSequence value) {
    this.task_group_id = value;
  }

  /**
   * Gets the value of the 'task_id' field.
   */
  public java.lang.CharSequence getTaskId() {
    return task_id;
  }

  /**
   * Sets the value of the 'task_id' field.
   * @param value the value to set.
   */
  public void setTaskId(java.lang.CharSequence value) {
    this.task_id = value;
  }

  /**
   * Gets the value of the 'start_time' field.
   */
  public java.lang.CharSequence getStartTime() {
    return start_time;
  }

  /**
   * Sets the value of the 'start_time' field.
   * @param value the value to set.
   */
  public void setStartTime(java.lang.CharSequence value) {
    this.start_time = value;
  }

  /**
   * Gets the value of the 'calcuate_latest_yn' field.
   */
  public java.lang.CharSequence getCalcuateLatestYn() {
    return calcuate_latest_yn;
  }

  /**
   * Sets the value of the 'calcuate_latest_yn' field.
   * @param value the value to set.
   */
  public void setCalcuateLatestYn(java.lang.CharSequence value) {
    this.calcuate_latest_yn = value;
  }

  /**
   * Gets the value of the 'data' field.
   */
  public java.util.List<java.lang.CharSequence> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.List<java.lang.CharSequence> value) {
    this.data = value;
  }

  /** Creates a new COL_ONEM2M RecordBuilder */
  public static com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder newBuilder() {
    return new com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder();
  }
  
  /** Creates a new COL_ONEM2M RecordBuilder by copying an existing Builder */
  public static com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder newBuilder(com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder other) {
    return new com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder(other);
  }
  
  /** Creates a new COL_ONEM2M RecordBuilder by copying an existing COL_ONEM2M instance */
  public static com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder newBuilder(com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M other) {
    return new com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder(other);
  }
  
  /**
   * RecordBuilder for COL_ONEM2M instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<COL_ONEM2M>
    implements org.apache.avro.data.RecordBuilder<COL_ONEM2M> {

    private java.lang.CharSequence col_from;
    private java.lang.CharSequence read_from_time;
    private java.lang.CharSequence write_queue_time;
    private java.lang.CharSequence task_group_id;
    private java.lang.CharSequence task_id;
    private java.lang.CharSequence start_time;
    private java.lang.CharSequence calcuate_latest_yn;
    private java.util.List<java.lang.CharSequence> data;

    /** Creates a new Builder */
    private Builder() {
      super(com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.col_from)) {
        this.col_from = data().deepCopy(fields()[0].schema(), other.col_from);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.read_from_time)) {
        this.read_from_time = data().deepCopy(fields()[1].schema(), other.read_from_time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.write_queue_time)) {
        this.write_queue_time = data().deepCopy(fields()[2].schema(), other.write_queue_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.task_group_id)) {
        this.task_group_id = data().deepCopy(fields()[3].schema(), other.task_group_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.task_id)) {
        this.task_id = data().deepCopy(fields()[4].schema(), other.task_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.start_time)) {
        this.start_time = data().deepCopy(fields()[5].schema(), other.start_time);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.calcuate_latest_yn)) {
        this.calcuate_latest_yn = data().deepCopy(fields()[6].schema(), other.calcuate_latest_yn);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.data)) {
        this.data = data().deepCopy(fields()[7].schema(), other.data);
        fieldSetFlags()[7] = true;
      }
    }
    
    /** Creates a Builder by copying an existing COL_ONEM2M instance */
    private Builder(com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M other) {
            super(com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.SCHEMA$);
      if (isValidValue(fields()[0], other.col_from)) {
        this.col_from = data().deepCopy(fields()[0].schema(), other.col_from);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.read_from_time)) {
        this.read_from_time = data().deepCopy(fields()[1].schema(), other.read_from_time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.write_queue_time)) {
        this.write_queue_time = data().deepCopy(fields()[2].schema(), other.write_queue_time);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.task_group_id)) {
        this.task_group_id = data().deepCopy(fields()[3].schema(), other.task_group_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.task_id)) {
        this.task_id = data().deepCopy(fields()[4].schema(), other.task_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.start_time)) {
        this.start_time = data().deepCopy(fields()[5].schema(), other.start_time);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.calcuate_latest_yn)) {
        this.calcuate_latest_yn = data().deepCopy(fields()[6].schema(), other.calcuate_latest_yn);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.data)) {
        this.data = data().deepCopy(fields()[7].schema(), other.data);
        fieldSetFlags()[7] = true;
      }
    }

    /** Gets the value of the 'col_from' field */
    public java.lang.CharSequence getColFrom() {
      return col_from;
    }
    
    /** Sets the value of the 'col_from' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setColFrom(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.col_from = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'col_from' field has been set */
    public boolean hasColFrom() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'col_from' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearColFrom() {
      col_from = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'read_from_time' field */
    public java.lang.CharSequence getReadFromTime() {
      return read_from_time;
    }
    
    /** Sets the value of the 'read_from_time' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setReadFromTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.read_from_time = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'read_from_time' field has been set */
    public boolean hasReadFromTime() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'read_from_time' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearReadFromTime() {
      read_from_time = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'write_queue_time' field */
    public java.lang.CharSequence getWriteQueueTime() {
      return write_queue_time;
    }
    
    /** Sets the value of the 'write_queue_time' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setWriteQueueTime(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.write_queue_time = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'write_queue_time' field has been set */
    public boolean hasWriteQueueTime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'write_queue_time' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearWriteQueueTime() {
      write_queue_time = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'task_group_id' field */
    public java.lang.CharSequence getTaskGroupId() {
      return task_group_id;
    }
    
    /** Sets the value of the 'task_group_id' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setTaskGroupId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.task_group_id = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'task_group_id' field has been set */
    public boolean hasTaskGroupId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'task_group_id' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearTaskGroupId() {
      task_group_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'task_id' field */
    public java.lang.CharSequence getTaskId() {
      return task_id;
    }
    
    /** Sets the value of the 'task_id' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setTaskId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.task_id = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'task_id' field has been set */
    public boolean hasTaskId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'task_id' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearTaskId() {
      task_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'start_time' field */
    public java.lang.CharSequence getStartTime() {
      return start_time;
    }
    
    /** Sets the value of the 'start_time' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setStartTime(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.start_time = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'start_time' field has been set */
    public boolean hasStartTime() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'start_time' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearStartTime() {
      start_time = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'calcuate_latest_yn' field */
    public java.lang.CharSequence getCalcuateLatestYn() {
      return calcuate_latest_yn;
    }
    
    /** Sets the value of the 'calcuate_latest_yn' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setCalcuateLatestYn(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.calcuate_latest_yn = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'calcuate_latest_yn' field has been set */
    public boolean hasCalcuateLatestYn() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'calcuate_latest_yn' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearCalcuateLatestYn() {
      calcuate_latest_yn = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'data' field */
    public java.util.List<java.lang.CharSequence> getData() {
      return data;
    }
    
    /** Sets the value of the 'data' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder setData(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[7], value);
      this.data = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'data' field has been set */
    public boolean hasData() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'data' field */
    public com.pineone.icbms.sda.comm.kafka.avro.COL_ONEM2M.Builder clearData() {
      data = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public COL_ONEM2M build() {
      try {
        COL_ONEM2M record = new COL_ONEM2M();
        record.col_from = fieldSetFlags()[0] ? this.col_from : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.read_from_time = fieldSetFlags()[1] ? this.read_from_time : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.write_queue_time = fieldSetFlags()[2] ? this.write_queue_time : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.task_group_id = fieldSetFlags()[3] ? this.task_group_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.task_id = fieldSetFlags()[4] ? this.task_id : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.start_time = fieldSetFlags()[5] ? this.start_time : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.calcuate_latest_yn = fieldSetFlags()[6] ? this.calcuate_latest_yn : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.data = fieldSetFlags()[7] ? this.data : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
